common: &common
  adapter: postgresql
  username:
  password:
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: rpg_dev

test:
  <<: *common
  database: rpg_test

production:
  <<: *common
  database: rpg
